#!/bin/bash

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y \
    apt-file \
    apt-transport-https \
    arandr \
    arptables \
    avr-libc \
    binutils-avr \
    avrdude \
    bash-completion \
    blueman \
    build-essential \
    bridge-utils \
    ca-certificates \
    cmake \
    coreutils \
    cryptsetup \
    curl \
    dnsutils \
    ebtables \
    feh \
    ffmpeg \
    file \
    fonts-powerline \
    gawk \
    gcc-avr \
    git \
    glusterfs-client \
    gnupg \
    htop \
    iftop \
    ifstat \
    iputils-ping \
    iptables \
    jq \
    keepassxc \
    libnotify-bin \
    libprotobuf-dev \
    libsqlite3-dev \
    libffi-dev \
    libssl-dev \
    light \
    locales-all \
    lsb-release \
    lsof \
    lvm2 \
    mdadm \
    moserial \
    minicom \
    mtr-tiny \
    neofetch \
    netcat \
    net-tools \
    network-manager \
    nitrogen \
    nmap \
    openssl \
    p7zip-full \
    powerline \
    protobuf-compiler \
    pv \
    pwgen \
    python3 \
    python3-pip \
    smartmontools \
    scdaemon \
    strace \
    sudo \
    sysstat \
    telnet \
    terminator \
    tcpdump \
    tmux \
    uuid-runtime \
    unzip \
    vim-nox \
    vlc \
    wget \
    yubikey-personalization \
    yubikey-personalization-gui \
    yubikey-luks \
    zip
