#!/bin/bash

ensure_ssh_agent () {
    if [ -f ~/.ssh/agent.env ] ; then
        . ~/.ssh/agent.env > /dev/null
        if ! kill -0 $SSH_AGENT_PID > /dev/null 2>&1; then
            echo "Stale agent file found. Spawning a new agent. "
            eval $(ssh-agent | tee ~/.ssh/agent.env)
        fi
    else
        echo "Starting ssh-agent"
        eval $(ssh-agent | tee ~/.ssh/agent.env)
    fi

    ln -sf "${SSH_AUTH_SOCK}" "${HOME}/.ssh/ssh-agent.sock"
    export SSH_AUTH_SOCK="${HOME}/.ssh/ssh-agent.sock"
}

kssh () {
    if [ "${1}" = "-9" ]; then 
        for session in $(pgrep -u "${USER}" -x ssh); do
            kill -9 "${session}"
        done;
    else
        pkill -U "${USER}" -x ssh
    fi
}

restart_ssh_agent () {
    pkill -U "${USER}" -x "ssh-agent"
    ensure_ssh_agent
}

ensure_ssh_agent
export SSH_AUTH_SOCK="${HOME}/.ssh/ssh-agent.sock"